"""Render a Stress Map snapshot (JSON) as STRESS-MAP.md.

Usage:  python export.py snapshot-YYYY-MM-DD.json > STRESS-MAP.md

The snapshot is a raw export of the private RFF Stress Map artifact's database
(meta, agreed phenomena, Claude's unagreed drafts). This script only formats it;
it changes no content.
"""
import json
import sys

STATUS = {
    "fits": "Fits naturally",
    "work": "Fits with work",
    "strains": "Strains",
    "breaks": "Breaks",
    "outside": "Outside an interpretation",
    "open": "Not yet examined",
}
ORDER = list(STATUS)
COLS = [
    "Geometry & time",
    "Quantum foundations",
    "Particles & fields",
    "Gravity & spacetime",
    "Cosmology",
]
FIELDS = [
    ("plain", "What it is"),
    ("needs", "Needs Neil's call"),
    ("rff", "RFF placement"),
    ("proposal", "Neil's proposal"),
    ("basis", "Built from"),
    ("assess", "Assessment"),
    ("next", "To work through"),
    ("prior", "Prior art"),
    ("session", "Worked through"),
]


def st(s):
    return STATUS.get(s, STATUS["open"])


def item_block(key, d, names, draft_of=None):
    out = [f"#### {d.get('name', key)}  `{key}`", ""]
    line = f"**Status:** {st(d.get('status'))}"
    if draft_of is not None:
        line += f" *(draft; agreed status: {st(draft_of)})*"
    out.append(line)
    deps = [names.get(x, x) for x in d.get("deps", [])]
    if deps:
        out.append(f"**Builds on:** {', '.join(deps)}")
    out.append("")
    for f, label in FIELDS:
        v = d.get(f)
        if v:
            out.append(f"- **{label}.** {v}")
    out.append("")
    return out


def main(path):
    snap = json.load(open(path, encoding="utf-8"))
    meta, ph, dr = snap["meta"], snap["phenomena"], snap["drafts"]
    names = {k: v.get("name", k) for k, v in ph.items()}
    names.update({k: v.get("name", k) for k, v in dr.items() if v.get("isNew")})

    o = ["# RFF Stress Map", ""]
    o.append(
        f"*Snapshot exported {snap['exported']} from the private Stress Map artifact "
        f"(map last updated {meta.get('updated', '?')}). Generated by "
        "[export.py](export.py) from [the raw snapshot](" + path.split("/")[-1] + "); "
        "edit the map, then re-export. Do not edit this file by hand.*"
    )
    o.append("")
    o.append(
        "> **Provisional.** Nothing on this map is done until all of it is done. "
        "Every status below, including \"fits naturally\", is provisional until every "
        "item has been examined and the whole map rechecked after the last merge."
    )
    o.append("")

    counts = {s: 0 for s in ORDER}
    for d in ph.values():
        counts[d.get("status") if d.get("status") in STATUS else "open"] += 1
    o += ["## Tally (agreed items)", "", "| Status | Count |", "|---|---|"]
    o += [f"| {STATUS[s]} | {counts[s]} |" for s in ORDER]
    o += [f"| **Total** | **{len(ph)}** |", ""]
    o += ["| Column | Examined / total |", "|---|---|"]
    for ci, c in enumerate(COLS):
        its = [d for d in ph.values() if d.get("col") == ci]
        ex = sum(1 for d in its if d.get("status") != "open")
        o.append(f"| {c} | {ex} / {len(its)} |")
    queue = sorted((k, d) for k, d in ph.items() if d.get("queued"))
    if queue:
        o += ["", "## Review queue", "", "*Items queued for Neil's review. Their status stays provisional until reviewed.*", ""]
        o += [f"- [ ] {d.get('name', k)} `{k}` — {st(d.get('status'))}, {COLS[d.get('col', 0)]} (queued {d['queued']})" for k, d in queue]
    o += ["", "## Framework commitments (as recorded on the map)", ""]
    o += [f"{i}. {t}" for i, t in enumerate(meta.get("commitments", []), 1)]
    if meta.get("questions"):
        o += ["", "**Open questions:** " + "; ".join(meta["questions"])]
    o += ["", "## Agreed map", ""]
    for ci, c in enumerate(COLS):
        o += [f"### {ci + 1}. {c}", ""]
        for k, d in sorted(
            ((k, d) for k, d in ph.items() if d.get("col") == ci),
            key=lambda kv: kv[1].get("ord", 0),
        ):
            o += item_block(k, d, names)
    o += [
        "## Claude's drafts — not agreed",
        "",
        "*Proposals waiting for Neil's review. None of this counts toward the map.*",
        "",
    ]
    for k, d in sorted(dr.items()):
        base = ph.get(k)
        merged = {**(base or {}), **{x: y for x, y in d.items() if x != "isNew"}}
        o += item_block(k, merged, names, None if base is None else base.get("status"))
    print("\n".join(o))


if __name__ == "__main__":
    main(sys.argv[1])
